import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#161c28",
        "on-tertiary-fixed": "#40000b",
        "secondary-fixed": "#e1e0ff",
        "primary-fixed": "#46ffb8",
        "inverse-primary": "#006c4a",
        "tertiary-fixed-dim": "#ffb3b4",
        "on-primary-fixed-variant": "#005236",
        "on-tertiary-fixed-variant": "#920024",
        "error": "#ffb4ab",
        "primary-container": "#00f0a8",
        "tertiary-fixed": "#ffdada",
        "surface": "#0d131f",
        "outline-variant": "#3b4a41",
        "on-background": "#dde2f4",
        "on-secondary-container": "#b0b2ff",
        "surface-tint": "#00e29e",
        "surface-container-lowest": "#080e1a",
        "on-primary": "#003824",
        "on-secondary": "#1000a9",
        "surface-bright": "#333947",
        "surface-container-high": "#242a37",
        "surface-container-highest": "#2f3542",
        "outline": "#84958a",
        "primary-fixed-dim": "#00e29e",
        "on-primary-container": "#006847",
        "surface-dim": "#0d131f",
        "on-tertiary-container": "#b80030",
        "on-secondary-fixed-variant": "#2f2ebe",
        "secondary-container": "#3131c0",
        "inverse-on-surface": "#2b303e",
        "on-secondary-fixed": "#07006c",
        "surface-container": "#1a202c",
        "tertiary": "#ffebeb",
        "surface-variant": "#2f3542",
        "on-error": "#690005",
        "primary": "#b7ffd9",
        "background": "#0d131f",
        "on-surface": "#dde2f4",
        "tertiary-container": "#ffc5c6",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#680017",
        "on-primary-fixed": "#002114",
        "on-surface-variant": "#b9cbbf",
        "secondary": "#c0c1ff",
        "inverse-surface": "#dde2f4"
      },
      spacing: {
        "space-sm": "0.375rem",
        "margin": "0.5rem",
        "space-lg": "0.75rem",
        "gutter-loose": "0.5rem",
        "space-xl": "1rem",
        "space-xs": "0.25rem",
        "space-md": "0.5rem",
        "gutter": "1px"
      },
      fontFamily: {
        sans: ["Geist", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [],
};
export default config;
