"""
core/signal_packet.py — Standardized Signal Data Contract

Strictly typed canonical signal packet generated by all strategies (Crypto, Stocks, AI).
Conforms to TRDENG architecture and SCHEMA.md contracts.
"""

from __future__ import annotations
import time
import uuid
from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, Any


@dataclass(frozen=True)
class SignalPacket:
    """
    Standardized, immutable signal packet emitted by any strategy plugin.
    
    Attributes:
        signal_id: Unique UUID identifier for audit tracing.
        strategy_id: Identifier of the issuing strategy (e.g. 'crypto_nfi_01', 'stock_orb_01').
        asset_class: Target asset class ('crypto' | 'stock' | 'futures').
        symbol: Ticker symbol (e.g. 'BTC-USD', 'AAPL').
        direction: Signed trade direction in [-1.0, 1.0]:
                   +1.0 = Full Long, -1.0 = Full Short, 0.0 = Flat/Neutral.
        conviction: Confidence/strength score in [0.0, 1.0].
        timestamp: UTC epoch timestamp when signal was generated.
        suggested_stop_pct: Strategy-recommended stop distance (fraction of price, e.g. 0.035).
        metadata: Strategy-specific telemetry context (e.g. indicator levels, entry reasons).
    """
    strategy_id: str
    asset_class: str
    symbol: str
    direction: float
    conviction: float
    signal_id: str = field(default_factory=lambda: f"sig_{uuid.uuid4().hex[:8]}")
    timestamp: float = field(default_factory=time.time)
    suggested_stop_pct: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        # Enforce direction bounds [-1.0, 1.0]
        clipped_dir = max(-1.0, min(1.0, float(self.direction)))
        object.__setattr__(self, "direction", clipped_dir)

        # Enforce conviction bounds [0.0, 1.0]
        clipped_conv = max(0.0, min(1.0, float(self.conviction)))
        object.__setattr__(self, "conviction", clipped_conv)

    def is_actionable(self, min_conviction: float = 0.50, min_direction: float = 0.05) -> bool:
        """Determines if the signal has sufficient magnitude and conviction to be evaluated."""
        return abs(self.direction) >= min_direction and self.conviction >= min_conviction

    def to_dict(self) -> Dict[str, Any]:
        """Serializes signal packet to dictionary."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> SignalPacket:
        """Constructs a SignalPacket from a dictionary, handling defaults gracefully."""
        return cls(
            strategy_id=str(data.get("strategy_id", "unknown_strat")),
            asset_class=str(data.get("asset_class", "crypto")),
            symbol=str(data.get("symbol", "")),
            direction=float(data.get("direction", 0.0)),
            conviction=float(data.get("conviction", 0.0)),
            signal_id=str(data.get("signal_id", f"sig_{uuid.uuid4().hex[:8]}")),
            timestamp=float(data.get("timestamp", time.time())),
            suggested_stop_pct=data.get("suggested_stop_pct"),
            metadata=dict(data.get("metadata", {}))
        )
